version: 'version'

services:
  nginx:
    build: .
    container_name: mynginx
    ports:
      - "8080:8080"
    volumes:
      - ./vol:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
